framework:
    cache:
        default_redis_provider: '%env(REDIS_APP_DSN)%'
        pools:
            app.cache:
                adapter: cache.adapter.redis
                provider: app.redis_app_provider