imports:
    - { resource: packages/ }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'

    # services
    App\:
        resource: '%kernel.project_dir%/src/*'
        exclude:
            - '%kernel.project_dir%/src/Kernel.php'
            - '%kernel.project_dir%/src/*/{Entity,Exception,Object,Payload,Response}'

    # controllers
    App\Controller\:
        resource: '%kernel.project_dir%/src/Controller'
        tags: ['controller.service_arguments']

    app.redis_app_provider:
        class: \Redis
        factory: [ 'Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection' ]
        arguments:
            - '%env(REDIS_DSN)%'

    app.simple_cache:
        class: Symfony\Component\Cache\Psr16Cache
        arguments:
            - '@app.cache'

    App\Service\CacheService:
        arguments:
            $redisProvider: '@app.redis_app_provider'
            $cacheAdapter: '@app.simple_cache'